## Clock signal
set_property PACKAGE_PIN W5 [get_ports i_Clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports i_Clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports i_Clk]
 
 ## Switches
set_property PACKAGE_PIN V17 [get_ports {i_Datos1[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_Datos1[0]}]
set_property PACKAGE_PIN V16 [get_ports {i_Datos1[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_Datos1[1]}]
set_property PACKAGE_PIN W16 [get_ports {i_Datos1[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_Datos1[2]}]
set_property PACKAGE_PIN W17 [get_ports {i_Datos1[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_Datos1[3]}]
set_property PACKAGE_PIN W15 [get_ports {i_Datos2[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_Datos2[0]}]
set_property PACKAGE_PIN V15 [get_ports {i_Datos2[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_Datos2[1]}]
set_property PACKAGE_PIN W14 [get_ports {i_Datos2[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_Datos2[2]}]
set_property PACKAGE_PIN W13 [get_ports {i_Datos2[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_Datos2[3]}]
set_property PACKAGE_PIN V2 [get_ports {i_Datos3[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_Datos3[0]}]
set_property PACKAGE_PIN T3 [get_ports {i_Datos3[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_Datos3[1]}]
set_property PACKAGE_PIN T2 [get_ports {i_Datos3[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_Datos3[2]}]
set_property PACKAGE_PIN R3 [get_ports {i_Datos3[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_Datos3[3]}]
set_property PACKAGE_PIN W2 [get_ports {i_Datos4[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_Datos4[0]}]
set_property PACKAGE_PIN U1 [get_ports {i_Datos4[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_Datos4[1]}]
set_property PACKAGE_PIN T1 [get_ports {i_Datos4[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_Datos4[2]}]
set_property PACKAGE_PIN R2 [get_ports {i_Datos4[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_Datos4[3]}]
 
 ##7 segment display
set_property PACKAGE_PIN W7 [get_ports {o_Segmentos[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_Segmentos[0]}]
set_property PACKAGE_PIN W6 [get_ports {o_Segmentos[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_Segmentos[1]}]
set_property PACKAGE_PIN U8 [get_ports {o_Segmentos[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_Segmentos[2]}]
set_property PACKAGE_PIN V8 [get_ports {o_Segmentos[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_Segmentos[3]}]
set_property PACKAGE_PIN U5 [get_ports {o_Segmentos[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_Segmentos[4]}]
set_property PACKAGE_PIN V5 [get_ports {o_Segmentos[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_Segmentos[5]}]
set_property PACKAGE_PIN U7 [get_ports {o_Segmentos[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_Segmentos[6]}]

#set_property PACKAGE_PIN V7 [get_ports dp]							
	#set_property IOSTANDARD LVCMOS33 [get_ports dp]

set_property PACKAGE_PIN U2 [get_ports {o_Anodo[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_Anodo[0]}]
set_property PACKAGE_PIN U4 [get_ports {o_Anodo[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_Anodo[1]}]
set_property PACKAGE_PIN V4 [get_ports {o_Anodo[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_Anodo[2]}]
set_property PACKAGE_PIN W4 [get_ports {o_Anodo[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_Anodo[3]}]


##Buttons
set_property PACKAGE_PIN U18 [get_ports i_Rst]						
	set_property IOSTANDARD LVCMOS33 [get_ports i_Rst]
